# -*- coding: utf-8 -*-
"""ParquetFileUpload.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QW-EjSsYJO7OQrxbSLKojHvMb4G6SFOW
"""

import boto3
import os

def upload_folder_to_s3(local_folder, bucket_name, s3_folder):
    s3_client = boto3.client('s3')
    for root, dirs, files in os.walk(local_folder):
        for file in files:
            local_path = os.path.join(root, file)
            relative_path = os.path.relpath(local_path, local_folder)
            s3_path = os.path.join(s3_folder, relative_path).replace("\\", "/")
            try:
                s3_client.upload_file(local_path, bucket_name, s3_path)
                print(f"Uploaded {local_path} to s3://{bucket_name}/{s3_path}")
            except Exception as e:
                print(f"Error uploading {local_path}: {e}")


local_folder = r'C:\Users\abhay\OneDrive\Desktop\Sapplica Files\parquet_output'
bucket_name = 'posdata-storage'
s3_folder = ''


upload_folder_to_s3(local_folder, bucket_name, s3_folder)

